# Generated by Django 3.1.1 on 2021-07-10 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_auto_20210708_1116'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LuggageBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='luggage_event', to='events.luggageevent', verbose_name='Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Luggage Booking',
                'verbose_name_plural': 'Luggage Bookings',
                'db_table': 'luggage_bookings',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Luggage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_type', models.PositiveIntegerField(choices=[(1, 'Box'), (2, 'Bags'), (3, 'Sacks/Ghana Must Go'), (4, 'Bucket')], verbose_name='Luggage Type')),
                ('size', models.PositiveIntegerField(choices=[(1, 'S'), (2, 'M'), (3, 'L'), (4, 'XL')], verbose_name='Luggage Size')),
                ('primary_color', models.CharField(max_length=15, verbose_name='Luggage Color')),
                ('secondary_color', models.CharField(blank=True, max_length=15, null=True, verbose_name='Luggage Color')),
                ('deposited', models.BooleanField(default=False, verbose_name='Deposited')),
                ('date_deposited', models.DateTimeField(blank=True, null=True, verbose_name='Date Deposited')),
                ('collected', models.BooleanField(default=False, verbose_name='Collected')),
                ('date_collected', models.DateTimeField(blank=True, null=True, verbose_name='Date Collected')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='luggage_booking', to='luggages.luggagebooking', verbose_name='Luggage Booking')),
            ],
            options={
                'verbose_name': 'Luggage',
                'verbose_name_plural': 'Luggages',
                'db_table': 'luggage',
                'managed': True,
            },
        ),
    ]
