# Generated by Django 3.1.1 on 2021-07-20 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('luggages', '0002_auto_20210717_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luggage',
            name='booking',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='luggage_booking', to='luggages.luggagebooking', verbose_name='Luggage Booking'),
        ),
    ]
