# Generated by Django 3.1.1 on 2021-07-25 14:06

from django.db import migrations, models
import django.db.models.deletion
import tradefair.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_auto_20210708_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('extra_image', models.ImageField(blank=True, null=True, upload_to=tradefair.models.image_directory, verbose_name='Image')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
            ],
            options={
                'verbose_name': 'Extra',
                'verbose_name_plural': 'Extras',
                'db_table': 'tradefair_extras',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('goods_image', models.ImageField(upload_to=tradefair.models.image_directory, verbose_name='Image')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
            ],
            options={
                'verbose_name': 'Goods',
                'verbose_name_plural': 'Goods',
                'db_table': 'tradefair_goods',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GoodsRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('slots', models.PositiveIntegerField(verbose_name='Slots')),
                ('used_slots', models.PositiveIntegerField(default=0, verbose_name='Used Slots')),
                ('available_slots', models.PositiveIntegerField(default=0, verbose_name='Available Slots')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_goods', to='events.tradefairevent', verbose_name='Event')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_register', to='tradefair.goods', verbose_name='Goods')),
            ],
            options={
                'verbose_name': 'Goods Register',
                'verbose_name_plural': 'Goods Registers',
                'db_table': 'tradefair_goods_register',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExtraRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('slots', models.PositiveIntegerField(verbose_name='Slots')),
                ('used_slots', models.PositiveIntegerField(default=0, verbose_name='Used Slots')),
                ('available_slots', models.PositiveIntegerField(default=0, verbose_name='Available Slots')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_extra', to='events.tradefairevent', verbose_name='Event')),
                ('extra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_register', to='tradefair.extra', verbose_name='Extra')),
            ],
            options={
                'verbose_name': 'Extra Register',
                'verbose_name_plural': 'Extra Registers',
                'db_table': 'tradefair_extra_register',
                'managed': True,
            },
        ),
    ]
