# Generated by Django 3.1.1 on 2021-07-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('reg_no', models.IntegerField(unique=True, verbose_name='Registration Number')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('admin', models.BooleanField(default=False, verbose_name='Admin')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('confirm', models.BooleanField(default=False, verbose_name='Confirmed')),
                ('confirmed_date', models.DateTimeField(blank=True, null=True, verbose_name='Confirmed Date')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
