# Generated by Django 3.1.1 on 2021-07-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportevent',
            name='payment_end_date',
            field=models.DateTimeField(verbose_name='Payment End Date'),
        ),
    ]
